services:
    netgen.ezforms.form.type.fieldtype.ezuser_create:
        class: Netgen\Bundle\EzFormsBundle\Form\Type\FieldType\UserCreateType
        tags:
            - { name: form.type, alias: ezforms_ezuser_create }

    netgen.ezforms.form.type.fieldtype.ezuser_update:
        class: Netgen\Bundle\EzFormsBundle\Form\Type\FieldType\UserUpdateType
        tags:
            - { name: form.type, alias: ezforms_ezuser_update }
