services:
    netgen.ezforms.form.data_mapper.create_content:
        class: Netgen\Bundle\EzFormsBundle\Form\DataMapper\CreateContentMapper
        arguments:
            - "@netgen.ezforms.form.fieldtype_handler_registry"

    netgen.ezforms.form.type.create_content:
        class: Netgen\Bundle\EzFormsBundle\Form\Type\CreateContentType
        arguments:
            - "@netgen.ezforms.form.fieldtype_handler_registry"
            - "@netgen.ezforms.form.data_mapper.create_content"
        tags:
            - { name: form.type, alias: ezforms_create_content }

    netgen.ezforms.form.data_mapper.create_user:
        class: Netgen\Bundle\EzFormsBundle\Form\DataMapper\CreateUserMapper
        arguments:
            - "@netgen.ezforms.form.fieldtype_handler_registry"

    netgen.ezforms.form.type.create_user:
        class: Netgen\Bundle\EzFormsBundle\Form\Type\CreateUserType
        arguments:
            - "@netgen.ezforms.form.fieldtype_handler_registry"
            - "@netgen.ezforms.form.data_mapper.create_user"
        tags:
            - { name: form.type, alias: ezforms_create_user }

    netgen.ezforms.form.data_mapper.update_content:
        class: Netgen\Bundle\EzFormsBundle\Form\DataMapper\UpdateContentMapper
        arguments:
            - "@netgen.ezforms.form.fieldtype_handler_registry"

    netgen.ezforms.form.type.update_content:
        class: Netgen\Bundle\EzFormsBundle\Form\Type\UpdateContentType
        arguments:
            - "@netgen.ezforms.form.fieldtype_handler_registry"
            - "@netgen.ezforms.form.data_mapper.update_content"
        tags:
            - { name: form.type, alias: ezforms_update_content }

    netgen.ezforms.form.data_mapper.update_user:
        class: Netgen\Bundle\EzFormsBundle\Form\DataMapper\UpdateUserMapper
        arguments:
            - "@netgen.ezforms.form.fieldtype_handler_registry"

    netgen.ezforms.form.type.update_user:
        class: Netgen\Bundle\EzFormsBundle\Form\Type\UpdateUserType
        arguments:
            - "@netgen.ezforms.form.fieldtype_handler_registry"
            - "@netgen.ezforms.form.data_mapper.update_user"
        tags:
            - { name: form.type, alias: ezforms_update_user }

    netgen.ezforms.form.url_type:
        class: Netgen\Bundle\EzFormsBundle\Form\Type\UrlType
        tags:
            - { name: form.type, alias: ezforms_url }

    netgen.ezforms.form.map_type:
        class: Netgen\Bundle\EzFormsBundle\Form\Type\MapType
        tags:
            - { name: form.type, alias: ezforms_map }

    netgen.ezforms.form.data_mapper.info_collection:
        class: Netgen\Bundle\EzFormsBundle\Form\DataMapper\InformationCollectionMapper
        arguments:
            - "@netgen.ezforms.form.fieldtype_handler_registry"

    netgen.ezforms.form.type.info_collection:
        class: Netgen\Bundle\EzFormsBundle\Form\Type\InformationCollectionType
        arguments:
            - "@netgen.ezforms.form.fieldtype_handler_registry"
            - "@netgen.ezforms.form.data_mapper.info_collection"
        calls:
            - [setLanguages, [$languages$]]
        tags:
            - { name: form.type, alias: ezforms_information_collection }
