_createcontent_route:
    path:   /democreatecontent
    defaults:   { _controller: NetgenEzFormsBundle:Demo:demoCreateContent }

_createuser_route:
    path:   /democreateuser
    defaults:   { _controller: NetgenEzFormsBundle:Demo:demoCreateUser }

_updatecontent_route:
    path:   /demoupdatecontent
    defaults:   { _controller: NetgenEzFormsBundle:Demo:demoUpdateContent }

_updateuser_route:
    path:   /demoupdateuser
    defaults:   { _controller: NetgenEzFormsBundle:Demo:demoUpdateUser }

_informationcollection_route:
    path: /demoinformationcollection
    defaults: { _controller: NetgenEzFormsBundle:Demo:demoInformationCollection }
