_createcontent_route:
    path: /democreatecontent
    controller: Netgen\Bundle\EzFormsBundle\Controller\DemoController::demoCreateContentAction

_createuser_route:
    path: /democreateuser
    controller: Netgen\Bundle\EzFormsBundle\Controller\DemoController::demoCreateUserAction

_updatecontent_route:
    path: /demoupdatecontent
    controller: Netgen\Bundle\EzFormsBundle\Controller\DemoController::demoUpdateContentAction

_updateuser_route:
    path: /demoupdateuser
    controller: Netgen\Bundle\EzFormsBundle\Controller\DemoController::demoUpdateUserAction

_informationcollection_route:
    path: /demoinformationcollection
    controller: Netgen\Bundle\EzFormsBundle\Controller\DemoController::demoInformationCollectionAction
